export const EXCHANGE_SWITCH = 'EXCHANGE_SWITCH';
export const FILTER_SWITCH = 'FILTER_SWITCH';

export const CURRENCY_CHANGE = 'CURRENCY_CHANGE';

export const BITFINEX_DATA_REQUEST = 'BITFINEX_DATA_REQUEST';
export const BITFINEX_DATA_SUCCESS = 'BITFINEX_DATA_SUCCESS';
export const BITFINEX_DATA_FAILURE = 'BITFINEX_DATA_FAILURE';
export const BITFINEX_DATA_CLEAR = 'BITFINEX_DATA_CLEAR';
export const BITFINEX_TICKERS_REQUEST = 'BITFINEX_TICKERS_REQUEST';
export const BITFINEX_TICKERS_SUCCESS = 'BITFINEX_TICKERS_SUCCESS';
export const BITFINEX_TICKERS_FAILURE = 'BITFINEX_TICKERS_FAILURE';

export const KRAKEN_DATA_REQUEST = 'KRAKEN_DATA_REQUEST';
export const KRAKEN_DATA_SUCCESS = 'KRAKEN_DATA_SUCCESS';
export const KRAKEN_DATA_FAILURE = 'KRAKEN_DATA_FAILURE';
export const KRAKEN_DATA_CLEAR = 'KRAKEN_DATA_CLEAR';
export const KRAKEN_TICKERS_REQUEST = 'KRAKEN_TICKERS_REQUEST';
export const KRAKEN_TICKERS_SUCCESS = 'KRAKEN_TICKERS_SUCCESS';
export const KRAKEN_TICKERS_FAILURE = 'KRAKEN_TICKERS_FAILURE';